### PR TITLE
replaces template name in helper declaration

### PR DESCRIPTION
**Pull request by SargntSprinkles**
I was trying to follow this tutorial and my app wasn't displaying any of the tasks. I checked the src folder for the step and found that the tutorial didn't match the example. This change fixed it for me.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Hi @SargntSprinkles thanks a lot for this PR, could you please sing the CLA as linked by @CLAassistant ?

**Comment by SargntSprinkles** [comment]
> Hi @SargntSprinkles thanks a lot for this PR, could you please sing the CLA as linked by @CLAassistant ?

Hello! I have signed it, but it continues to show `not signed yet` here.

Screen Shot 2021-06-07 at 10 00 34 AM

**Comment by StorytellerCZ** [comment]
@SargntSprinkles Try clicking this link: https://cla-assistant.io/check/meteor/blaze-tutorial?pullRequest=16
If that doesn't help then maybe adding a commit should trigger it again.

**Comment by SargntSprinkles** [comment]
@StorytellerCZ I have clicked that link many times. I also added a commit to trigger the check. It's still showing `not signed yet`.

**Pull request merged**
